import type { Customer, Company, ContactPerson, LeadOpportunity, WonJob, Activity, Task, StaffMember, TeamMember } from '@/types'

// Mock team — stands in for the Supabase `users` table (Google sign-ins) when
// running locally on mock data. Names match existing mock leads' owner fields.
export const mockTeamMembers: TeamMember[] = [
  { id: 'u-vitta', name: 'Vitta', email: 'vitta@sixsheet.me', role: 'admin' },
  { id: 'u-andy', name: 'Andy', email: 'andy@sixsheet.me', role: 'operation' },
  { id: 'u-fern', name: 'Fern', email: 'fern@sixsheet.me', role: 'sales' },
  { id: 'u-nong', name: 'Nong', email: 'nong@sixsheet.me', role: 'operation' },
]

// Back-compat: name-only list (some callers just need owner names).
export const MOCK_USERS = mockTeamMembers.map((m) => m.name)

// ─── Customers ───────────────────────────────────────────────────────────────
export const mockCustomers: Customer[] = [
  {
    customer_id: 'cust-001',
    company_name: 'Sephora Thailand',
    contact_person: 'Khun Pim',
    phone: '081-234-5678',
    email: 'pim.mkt@sephora.co.th',
    line_id: '@sephorath',
    social: '@sephorathailand',
    customer_type: 'brand',
    notes: 'Repeat client. Usually books LCA + Film combo. Prefers EastinGrand or EmQuartier.',
    created_at: '2025-01-10T09:00:00Z',
    updated_at: '2026-05-01T10:00:00Z',
  },
  {
    customer_id: 'cust-002',
    company_name: 'LINE Thailand',
    contact_person: 'Khun Toy',
    phone: '089-876-5432',
    email: 'toy@linecorp.th',
    line_id: 'toy_lineth',
    social: '@linethai_events',
    customer_type: 'brand',
    notes: 'Usually activates at Central World or Icon Siam. Big budgets.',
    created_at: '2025-03-15T10:00:00Z',
    updated_at: '2026-04-20T08:30:00Z',
  },
  {
    customer_id: 'cust-003',
    company_name: 'KBANK',
    contact_person: 'Khun Winn',
    phone: '062-111-2233',
    email: 'winn.event@kasikornbank.com',
    line_id: 'winn_kbank',
    social: '',
    customer_type: 'brand',
    notes: 'Corporate client. Staff parties and product launches.',
    created_at: '2025-06-01T08:00:00Z',
    updated_at: '2026-03-10T14:00:00Z',
  },
  {
    customer_id: 'cust-004',
    company_name: 'EastinGrand Sathorn',
    contact_person: 'Khun Ploy',
    phone: '02-210-8100',
    email: 'events@eastingrand.com',
    line_id: '',
    social: '',
    customer_type: 'venue',
    notes: 'Venue partner. Refer clients to us regularly.',
    created_at: '2025-07-01T07:00:00Z',
    updated_at: '2025-12-01T09:00:00Z',
  },
  {
    customer_id: 'cust-005',
    company_name: 'Lazada Thailand',
    contact_person: 'Khun Mint',
    phone: '096-555-7788',
    email: 'mint.brand@lazada.co.th',
    line_id: 'mint_lazada',
    social: '@lazadath',
    customer_type: 'brand',
    notes: '11.11, 12.12 campaigns. Good partner for SX Event.',
    created_at: '2025-08-20T09:00:00Z',
    updated_at: '2026-05-10T11:00:00Z',
  },
  {
    customer_id: 'cust-006',
    company_name: 'PTT Group',
    contact_person: 'Khun Som',
    phone: '081-400-9900',
    email: 'som.csr@pttplc.com',
    line_id: '',
    social: '',
    customer_type: 'brand',
    notes: 'CSR & Family Day events. Usually outdoor or PTT HQ.',
    created_at: '2025-09-05T08:00:00Z',
    updated_at: '2026-02-14T10:00:00Z',
  },
  {
    customer_id: 'cust-007',
    company_name: 'MUJI Thailand',
    contact_person: 'Khun Aom',
    phone: '02-000-1111',
    email: 'aom@muji.co.th',
    line_id: 'aom_muji',
    social: '',
    customer_type: 'brand',
    notes: 'New brand client. Store opening & in-store events.',
    created_at: '2026-04-01T08:00:00Z',
    updated_at: '2026-05-10T10:00:00Z',
  },
  {
    customer_id: 'cust-008',
    company_name: 'Chanel Thailand',
    contact_person: 'Khun Belle',
    phone: '096-555-0039',
    email: 'belle@chanel.th',
    line_id: 'belle_chanel',
    social: '',
    customer_type: 'brand',
    notes: 'VIP/luxury client. Premium materials only. Strict brand guidelines.',
    created_at: '2026-04-15T09:00:00Z',
    updated_at: '2026-05-12T11:00:00Z',
  },
  {
    customer_id: 'cust-009',
    company_name: 'Central Food Hall',
    contact_person: 'Khun Nook',
    phone: '062-333-0040',
    email: 'nook@central.co.th',
    line_id: 'nook_central',
    social: '',
    customer_type: 'venue',
    notes: 'Roadshow & sampling events in Central Group malls.',
    created_at: '2026-03-01T08:00:00Z',
    updated_at: '2026-05-01T09:00:00Z',
  },
  {
    customer_id: 'cust-010',
    company_name: 'LINE MAN Thailand',
    contact_person: 'Khun Kob',
    phone: '089-900-0042',
    email: 'kob@linecorp.th',
    line_id: 'kob_lineman',
    social: '@lineman_th',
    customer_type: 'brand',
    notes: 'Weekend market and food delivery promo activations.',
    created_at: '2026-04-20T09:00:00Z',
    updated_at: '2026-05-08T09:00:00Z',
  },
  {
    customer_id: 'cust-011',
    company_name: 'Siam Paragon',
    contact_person: 'Khun Wan',
    phone: '081-555-6677',
    email: 'wan.events@siamparagon.co.th',
    line_id: 'wan_siam',
    social: '',
    customer_type: 'venue',
    notes: 'Premium mall venue. Roadshow & beauty events. Billing on Wednesdays.',
    created_at: '2026-04-10T09:00:00Z',
    updated_at: '2026-05-10T14:00:00Z',
  },
  {
    customer_id: 'cust-012',
    company_name: 'Marriott Hotels Thailand',
    contact_person: 'Khun Fah',
    phone: '086-444-5566',
    email: 'fah.events@marriott.com',
    line_id: 'fah_marriott',
    social: '',
    customer_type: 'venue',
    notes: 'Corporate staff parties & gala dinners. Wants to rebook Q4 2026.',
    created_at: '2025-10-01T10:00:00Z',
    updated_at: '2025-12-22T09:00:00Z',
  },
]

// ─── Companies ───────────────────────────────────────────────────────────────
// One Company = one legal/billing entity. Phone/email here are company-level.
// Banking fields populated from WonJob.company_account where available.
export const mockCompanies: Company[] = [
  {
    company_id: 'comp-001',
    company_name: 'Sephora Thailand',
    company_type: 'brand',
    phone: '081-234-5678',
    email: 'pim.mkt@sephora.co.th',
    line_id: '@sephorath',
    social: '@sephorathailand',
    notes: 'Repeat client. Usually books LCA + Film combo. Prefers EastinGrand or EmQuartier.',
    created_at: '2025-01-10T09:00:00Z',
    updated_at: '2026-05-01T10:00:00Z',
  },
  {
    company_id: 'comp-002',
    company_name: 'LINE Thailand',
    company_type: 'brand',
    phone: '089-876-5432',
    email: 'toy@linecorp.th',
    line_id: 'toy_lineth',
    social: '@linethai_events',
    notes: 'Usually activates at Central World or Icon Siam. Big budgets.',
    created_at: '2025-03-15T10:00:00Z',
    updated_at: '2026-04-20T08:30:00Z',
  },
  {
    company_id: 'comp-003',
    company_name: 'KBANK',
    company_type: 'brand',
    phone: '062-111-2233',
    email: 'winn.event@kasikornbank.com',
    line_id: 'winn_kbank',
    notes: 'Corporate client. Staff parties and product launches.',
    created_at: '2025-06-01T08:00:00Z',
    updated_at: '2026-03-10T14:00:00Z',
  },
  {
    company_id: 'comp-004',
    company_name: 'EastinGrand Sathorn',
    company_type: 'venue',
    phone: '02-210-8100',
    email: 'events@eastingrand.com',
    notes: 'Venue partner. Refer clients to us regularly.',
    created_at: '2025-07-01T07:00:00Z',
    updated_at: '2025-12-01T09:00:00Z',
  },
  {
    company_id: 'comp-005',
    company_name: 'Lazada Thailand',
    company_type: 'brand',
    phone: '096-555-7788',
    email: 'mint.events@lazada.co.th',
    line_id: 'mint_lazada',
    social: '@lazadath',
    // Billing info from job-007
    tax_id: '0105557107132',
    registered_address: '29/F, Bhiraj Tower, 2096 Sukhumvit Rd, Bangkok 10110',
    branch_name: 'สำนักงานใหญ่',
    bank_name: 'BBL',
    bank_account_number: '7890100007',
    bank_account_name: 'Lazada Thailand Co., Ltd.',
    bank_branch: 'สาขาสุขุมวิท',
    billing_notes: 'PO number required — ขอจาก Mint ก่อน issue invoice',
    notes: '11.11, 12.12 campaigns. Good partner for SX Event.',
    created_at: '2025-08-20T09:00:00Z',
    updated_at: '2026-05-10T11:00:00Z',
  },
  {
    company_id: 'comp-006',
    company_name: 'PTT Group',
    company_type: 'brand',
    phone: '081-400-9900',
    email: 'som.csr@pttplc.com',
    notes: 'CSR & Family Day events. Usually outdoor or PTT HQ.',
    created_at: '2025-09-05T08:00:00Z',
    updated_at: '2026-02-14T10:00:00Z',
  },
  {
    company_id: 'comp-007',
    company_name: 'MUJI Thailand',
    company_type: 'brand',
    phone: '02-000-1111',
    email: 'aom@muji.co.th',
    line_id: 'aom_muji',
    // Billing info from job-001
    branch_name: 'Head Office',
    bank_name: 'SCB',
    bank_account_number: '1234500001',
    bank_account_name: 'MUJI Thailand Co., Ltd.',
    bank_branch: 'สาขาเซ็นทรัลเวิลด์',
    notes: 'New brand client. Store opening & in-store events.',
    created_at: '2026-04-01T08:00:00Z',
    updated_at: '2026-05-10T10:00:00Z',
  },
  {
    company_id: 'comp-008',
    company_name: 'Chanel Thailand',
    company_type: 'brand',
    phone: '096-555-0039',
    email: 'belle@chanel.th',
    line_id: 'belle_chanel',
    // Billing info from job-002
    tax_id: '0105556000001',
    registered_address: 'Gaysorn Village, Ploenchit Rd',
    branch_name: 'Head Office',
    bank_name: 'KBANK',
    bank_account_number: '2345600002',
    bank_account_name: 'Chanel Thailand Ltd.',
    bank_branch: 'สาขาเพลินจิต',
    billing_notes: 'ส่งบิลล่วงหน้า 30 วัน',
    notes: 'VIP/luxury client. Premium materials only. Strict brand guidelines.',
    created_at: '2026-04-15T09:00:00Z',
    updated_at: '2026-05-12T11:00:00Z',
  },
  {
    company_id: 'comp-009',
    company_name: 'Central Food Hall',
    company_type: 'venue',
    phone: '062-333-0040',
    email: 'nook@central.co.th',
    line_id: 'nook_central',
    // Billing info from job-003
    tax_id: '0105540000001',
    registered_address: '1027 Ploenchit Rd, Lumpini, Bangkok',
    branch_name: 'Head Office',
    bank_name: 'BBL',
    bank_account_number: '3456700003',
    bank_account_name: 'Central Food Retail Co., Ltd.',
    bank_branch: 'สาขาชิดลม',
    notes: 'Roadshow & sampling events in Central Group malls.',
    created_at: '2026-03-01T08:00:00Z',
    updated_at: '2026-05-01T09:00:00Z',
  },
  {
    company_id: 'comp-010',
    company_name: 'LINE MAN Thailand',
    company_type: 'brand',
    phone: '089-900-0042',
    email: 'kob@linecorp.th',
    line_id: 'kob_lineman',
    social: '@lineman_th',
    // Billing info from job-005
    tax_id: '0105558000001',
    registered_address: 'Gaysorn Tower, Ploenchit',
    branch_name: 'Head Office',
    bank_name: 'SCB',
    bank_account_number: '5678900005',
    bank_account_name: 'Line Company (Thailand) Ltd.',
    bank_branch: 'สาขาเพลินจิต',
    billing_notes: 'Credit 30 วัน',
    notes: 'Weekend market and food delivery promo activations.',
    created_at: '2026-04-20T09:00:00Z',
    updated_at: '2026-05-08T09:00:00Z',
  },
  {
    company_id: 'comp-011',
    company_name: 'Siam Paragon',
    company_type: 'venue',
    phone: '081-555-6677',
    email: 'wan.events@siamparagon.co.th',
    line_id: 'wan_siam',
    // Billing info from job-006
    tax_id: '0105537059873',
    registered_address: '991 Rama I Rd, Pathum Wan, Bangkok 10330',
    branch_name: 'สำนักงานใหญ่',
    bank_name: 'KBANK',
    bank_account_number: '6789000006',
    bank_account_name: 'Siam Paragon Development Co., Ltd.',
    bank_branch: 'สาขาสยามพารากอน',
    billing_notes: 'วางบิลทุกวันพุธ ส่งเอกสาร PDF ทาง email',
    notes: 'Premium mall venue. Roadshow & beauty events.',
    created_at: '2026-04-10T09:00:00Z',
    updated_at: '2026-05-10T14:00:00Z',
  },
  {
    company_id: 'comp-012',
    company_name: 'Marriott Hotels Thailand',
    company_type: 'venue',
    phone: '086-444-5566',
    email: 'fah.events@marriott.com',
    line_id: 'fah_marriott',
    // Billing info from job-008
    tax_id: '0105520009876',
    registered_address: '4 Sukhumvit Soi 2, Klongtoey, Bangkok 10110',
    branch_name: 'สำนักงานใหญ่',
    bank_name: 'TTB',
    bank_account_number: '8901200008',
    bank_account_name: 'JW Marriott Bangkok',
    bank_branch: 'สาขาสุขุมวิท 2',
    billing_notes: 'ส่ง invoice ทาง email ภายใน 7 วันหลังงาน',
    notes: 'Corporate staff parties & gala dinners. Wants to rebook Q4 2026.',
    created_at: '2025-10-01T10:00:00Z',
    updated_at: '2025-12-22T09:00:00Z',
  },
]

// ─── ContactPersons ───────────────────────────────────────────────────────────
// One ContactPerson = one named individual under a Company.
// company_id is required — every contact belongs to a company.
export const mockContactPersons: ContactPerson[] = [
  {
    contact_id: 'ctct-001',
    company_id: 'comp-001',
    name: 'Khun Pim',
    phone: '081-234-5678',
    email: 'pim.mkt@sephora.co.th',
    line_id: '@sephorath',
    role: 'Marketing Manager',
    created_at: '2025-01-10T09:00:00Z',
    updated_at: '2026-05-01T10:00:00Z',
  },
  {
    contact_id: 'ctct-002',
    company_id: 'comp-002',
    name: 'Khun Toy',
    phone: '089-876-5432',
    email: 'toy@linecorp.th',
    line_id: 'toy_lineth',
    role: 'Event Coordinator',
    created_at: '2025-03-15T10:00:00Z',
    updated_at: '2026-04-20T08:30:00Z',
  },
  {
    contact_id: 'ctct-003',
    company_id: 'comp-003',
    name: 'Khun Winn',
    phone: '062-111-2233',
    email: 'winn.event@kasikornbank.com',
    line_id: 'winn_kbank',
    role: 'Event Manager',
    created_at: '2025-06-01T08:00:00Z',
    updated_at: '2026-03-10T14:00:00Z',
  },
  {
    contact_id: 'ctct-004',
    company_id: 'comp-004',
    name: 'Khun Ploy',
    phone: '02-210-8100',
    email: 'events@eastingrand.com',
    role: 'Events & Catering Manager',
    created_at: '2025-07-01T07:00:00Z',
    updated_at: '2025-12-01T09:00:00Z',
  },
  {
    contact_id: 'ctct-005',
    company_id: 'comp-005',
    name: 'Khun Mint',
    phone: '096-555-7788',
    email: 'mint.brand@lazada.co.th',
    line_id: 'mint_lazada',
    role: 'Brand & Events',
    created_at: '2025-08-20T09:00:00Z',
    updated_at: '2026-05-10T11:00:00Z',
  },
  {
    contact_id: 'ctct-006',
    company_id: 'comp-006',
    name: 'Khun Som',
    phone: '081-400-9900',
    email: 'som.csr@pttplc.com',
    role: 'CSR Manager',
    created_at: '2025-09-05T08:00:00Z',
    updated_at: '2026-02-14T10:00:00Z',
  },
  {
    contact_id: 'ctct-007',
    company_id: 'comp-007',
    name: 'Khun Aom',
    phone: '02-000-1111',
    email: 'aom@muji.co.th',
    line_id: 'aom_muji',
    role: 'Store Marketing',
    created_at: '2026-04-01T08:00:00Z',
    updated_at: '2026-05-10T10:00:00Z',
  },
  {
    contact_id: 'ctct-008',
    company_id: 'comp-008',
    name: 'Khun Belle',
    phone: '096-555-0039',
    email: 'belle@chanel.th',
    line_id: 'belle_chanel',
    role: 'PR & Events',
    created_at: '2026-04-15T09:00:00Z',
    updated_at: '2026-05-12T11:00:00Z',
  },
  {
    contact_id: 'ctct-009',
    company_id: 'comp-009',
    name: 'Khun Nook',
    phone: '062-333-0040',
    email: 'nook@central.co.th',
    line_id: 'nook_central',
    role: 'Promotions & Events',
    created_at: '2026-03-01T08:00:00Z',
    updated_at: '2026-05-01T09:00:00Z',
  },
  {
    contact_id: 'ctct-010',
    company_id: 'comp-010',
    name: 'Khun Kob',
    phone: '089-900-0042',
    email: 'kob@linecorp.th',
    line_id: 'kob_lineman',
    role: 'Brand Activation',
    created_at: '2026-04-20T09:00:00Z',
    updated_at: '2026-05-08T09:00:00Z',
  },
  {
    contact_id: 'ctct-011',
    company_id: 'comp-011',
    name: 'Khun Wan',
    phone: '081-555-6677',
    email: 'wan.events@siamparagon.co.th',
    line_id: 'wan_siam',
    role: 'Venue Events Manager',
    created_at: '2026-04-10T09:00:00Z',
    updated_at: '2026-05-10T14:00:00Z',
  },
  {
    contact_id: 'ctct-012',
    company_id: 'comp-012',
    name: 'Khun Fah',
    phone: '086-444-5566',
    email: 'fah.events@marriott.com',
    line_id: 'fah_marriott',
    role: 'Event Sales Manager',
    created_at: '2025-10-01T10:00:00Z',
    updated_at: '2025-12-22T09:00:00Z',
  },
]

// ─── Leads & Opportunities ───────────────────────────────────────────────────
export const mockLeadOpportunities: LeadOpportunity[] = [
  {
    lead_op_id: 'lop-001',
    name: 'Sephora Annual Campaign 2026',
    company_id: 'comp-001',
    contact_person_id: 'ctct-001',
    customer_id: 'cust-001',
    customer_name: 'Sephora Thailand',
    contact_person: 'Khun Pim',
    service_type: 'CAP*TURES',
    event_date: '2026-07-15',
    venue: 'EastinGrand Sathorn',
    estimated_value: 150000,
    owner: 'Vitta',
    notes: 'Full CAP*TURES set + printed strips. Wants 3D backdrop design.',
    status: 'open',
    created_at: '2026-04-10T09:00:00Z',
    updated_at: '2026-05-12T10:00:00Z',
  },
  {
    lead_op_id: 'lop-002',
    name: 'KBANK Staff Appreciation Day',
    company_id: 'comp-003',
    contact_person_id: 'ctct-003',
    customer_id: 'cust-003',
    customer_name: 'KBANK',
    contact_person: 'Khun Winn',
    service_type: 'Andy & Fine',
    event_date: '2026-06-20',
    venue: 'KBANK HQ Auditorium',
    estimated_value: 85000,
    owner: 'Andy',
    notes: 'Branding with KBANK green. Staff of ~300 pax.',
    status: 'open',
    created_at: '2026-04-20T10:30:00Z',
    updated_at: '2026-05-10T09:00:00Z',
  },
  {
    lead_op_id: 'lop-003',
    name: 'LINE Thailand Mid-Year Festival',
    company_id: 'comp-002',
    contact_person_id: 'ctct-002',
    customer_id: 'cust-002',
    customer_name: 'LINE Thailand',
    contact_person: 'Khun Toy',
    service_type: 'SX Event',
    event_date: '2026-08-02',
    venue: 'Central World',
    estimated_value: 220000,
    owner: 'Fern',
    notes: 'Multi-day activation. 4 booths, LCA + Film + GIF.',
    status: 'open',
    created_at: '2026-05-01T08:00:00Z',
    updated_at: '2026-05-14T11:00:00Z',
  },
  {
    lead_op_id: 'lop-004',
    name: 'K.Nong + K.Tan Wedding Photo',
    // No company/contact in DB — private individual client
    company_id: undefined,
    contact_person_id: undefined,
    customer_id: undefined,
    customer_name: 'K.Nong Thanaporn',
    contact_person: 'K.Nong',
    service_type: 'CAP*TURES',
    event_date: '2026-09-28',
    venue: 'Capella Bangkok',
    estimated_value: 45000,
    owner: 'Nong',
    notes: 'Private wedding. Romantic film strip style.',
    status: 'open',
    created_at: '2026-05-08T14:00:00Z',
    updated_at: '2026-05-08T14:00:00Z',
  },
  {
    lead_op_id: 'lop-005',
    name: 'Lazada 11.11 Campaign 2025',
    company_id: 'comp-005',
    contact_person_id: 'ctct-005',
    customer_id: 'cust-005',
    customer_name: 'Lazada Thailand',
    contact_person: 'Khun Mint',
    service_type: 'CAP*TURES',
    event_date: '2025-11-11',
    venue: 'Icon Siam',
    estimated_value: 180000,
    owner: 'Vitta',
    notes: 'Already confirmed and delivered. Invoice paid.',
    status: 'won',
    created_at: '2025-09-15T09:00:00Z',
    updated_at: '2025-11-15T12:00:00Z',
  },
  {
    lead_op_id: 'lop-006',
    name: 'Marriott Staff Year-End Party',
    company_id: 'comp-012',
    contact_person_id: 'ctct-012',
    customer_id: undefined,
    customer_name: 'Marriott Hotels Thailand',
    contact_person: 'Khun Fah',
    service_type: 'Andy & Fine',
    event_date: '2025-12-20',
    venue: 'JW Marriott Bangkok',
    estimated_value: 60000,
    owner: 'Andy',
    notes: 'Year-end dinner party. 200 pax. Won and delivered.',
    status: 'won',
    created_at: '2025-10-10T10:00:00Z',
    updated_at: '2025-12-22T09:00:00Z',
  },
  {
    lead_op_id: 'lop-007',
    name: 'AIS Summer Activation 2025',
    // AIS not in company DB — no FK
    company_id: undefined,
    contact_person_id: undefined,
    customer_id: undefined,
    customer_name: 'AIS',
    contact_person: 'Khun Mod',
    service_type: 'SX Event',
    event_date: '2025-06-15',
    venue: 'Siam Paragon',
    estimated_value: 300000,
    owner: 'Fern',
    notes: 'Budget too low after procurement cut.',
    status: 'lost',
    created_at: '2025-04-01T09:00:00Z',
    updated_at: '2025-05-20T16:00:00Z',
  },
]

// ─── Staff Registry ───────────────────────────────────────────────────────────
export const mockStaff: StaffMember[] = [
  {
    staff_id: 'staff-001',
    name: 'นายสมชาย วงศ์ไพบูลย์',
    nickname: 'ชาย',
    phone: '081-234-5001',
    bank_name: 'SCB',
    bank_account_number: '1234567890',
    bank_account_name: 'สมชาย วงศ์ไพบูลย์',
    bank_branch: 'สาขาสยามสแควร์',
  },
  {
    staff_id: 'staff-002',
    name: 'นางสาวปิยะนุช ทองดี',
    nickname: 'นุช',
    phone: '089-876-5002',
    bank_name: 'KBANK',
    bank_account_number: '0987654321',
    bank_account_name: 'ปิยะนุช ทองดี',
    bank_branch: 'สาขาอโศก',
  },
  {
    staff_id: 'staff-003',
    name: 'นายกิตติพงศ์ แสงอรุณ',
    nickname: 'กิต',
    phone: '062-111-5003',
    bank_name: 'BBL',
    bank_account_number: '1122334455',
    bank_account_name: 'กิตติพงศ์ แสงอรุณ',
    bank_branch: 'สาขาสีลม',
  },
  {
    staff_id: 'staff-004',
    name: 'นางสาวรัตนา มีสุข',
    nickname: 'รัต',
    phone: '096-555-5004',
    bank_name: 'TTB',
    bank_account_number: '6677889900',
    bank_account_name: 'รัตนา มีสุข',
    bank_branch: 'สาขาเอกมัย',
  },
]

// ─── Won Jobs (OP Kanban) ─────────────────────────────────────────────────────
// Title format: YYYY.MM.DD - JOB_ID - PRODUCT_TYPE - PRODUCT_CAT - PRODUCT_NAME@PLACE
export const mockWonJobs: WonJob[] = [
  {
    job_id: 'job-001',
    // Title: 2026.06.05 - 038 - CAP*TURES - Event - MUJI@CentralEmbassy
    job_number: '038',
    event_date: '2026-06-05',
    product_type: 'CAP*TURES',
    product_cat: 'Event',
    product_name: 'MUJI',
    place: 'CentralEmbassy',
    // รายละเอียดงาน
    event_display_name: 'MUJI Central Embassy Store Opening',
    event_time: '11.00-19.00',
    venue: 'MUJI Central Embassy, 1st Floor',
    job_detail_notes: 'CAP*TURES Photobooth พร้อม Print\nBackdrop ลูกค้า (MUJI Brand)\nNew brand — ขอ full brand kit ก่อนออกแบบ AW',
    // ข้อมูลหน้างาน
    onsite_contact_name: 'Khun Aom',
    onsite_contact_phone: '081-234-0001',
    onsite_line_id: 'aom_muji',
    install_point: 'ชั้น 1 หน้าร้าน ติดกับ entrance',
    team_meeting_time: '09.00',
    onsite_notes: '',
    staff_list: [],
    // Company Account
    company_account: {
      company_name: 'MUJI Thailand Co., Ltd.',
      contact_point: 'Khun Aom',
      phone_number: '02-000-1111',
      line_id: '',
      email: 'aom@muji.co.th',
      tax_id: '',
      company_address: '',
      branch: 'Head Office',
      billing_notes: '',
      bank_name: 'SCB',
      bank_account_number: '1234500001',
      bank_account_name: 'MUJI Thailand Co., Ltd.',
      bank_branch: 'สาขาเซ็นทรัลเวิลด์',
    },
    company_id: 'comp-007',
    contact_person_id: 'ctct-007',
    customer_name: 'MUJI Thailand',
    customer_id: 'cust-007',
    lead_op_id: undefined,
    estimated_value: 55000,
    payment_status: 'unpaid',
    staff_status: 'pending',
    doc_status: 'pending',
    op_stage: 'WON_JOB_LIST',
    owner: 'Vitta',
    created_at: '2026-05-10T10:00:00Z',
    updated_at: '2026-05-10T10:00:00Z',
  position: 0,
  },
  {
    job_id: 'job-002',
    // Title: 2026.06.12 - 039 - Andy & Fine - Event - Chanel@Capella
    job_number: '039',
    event_date: '2026-06-12',
    product_type: 'Andy & Fine',
    product_cat: 'Event',
    product_name: 'Chanel',
    place: 'Capella',
    // รายละเอียดงาน
    event_display_name: 'Chanel VIP Dinner 2026',
    event_time: '18.00-23.00',
    venue: 'Capella Bangkok, River Terrace',
    job_detail_notes: 'Andy & Fine portrait station พร้อม premium print\nBackdrop ขาว + Chanel logo ทอง\nVIP-only event. ใช้กระดาษ premium เท่านั้น',
    // ข้อมูลหน้างาน
    onsite_contact_name: 'Khun Belle',
    onsite_contact_phone: '096-555-0039',
    onsite_line_id: 'belle_chanel',
    install_point: 'River Terrace ชั้น G',
    team_meeting_time: '15.00',
    onsite_notes: 'Dress code black tie. ทีมต้องแต่งกายสุภาพ',
    staff_list: [],
    // Company Account
    company_account: {
      company_name: 'Chanel Thailand Ltd.',
      contact_point: 'Khun Belle',
      phone_number: '02-000-2222',
      line_id: 'belle_chanel',
      email: 'belle@chanel.th',
      tax_id: '0105556000001',
      company_address: 'Gaysorn Village, Ploenchit Rd',
      branch: 'Head Office',
      billing_notes: 'ส่งบิลล่วงหน้า 30 วัน',
      bank_name: 'KBANK',
      bank_account_number: '2345600002',
      bank_account_name: 'Chanel Thailand Ltd.',
      bank_branch: 'สาขาเพลินจิต',
    },
    company_id: 'comp-008',
    contact_person_id: 'ctct-008',
    customer_name: 'Chanel Thailand',
    customer_id: 'cust-008',
    lead_op_id: undefined,
    estimated_value: 120000,
    payment_status: 'partial',
    staff_status: 'pending',
    doc_status: 'pending',
    op_stage: 'WON_JOB_LIST',
    owner: 'Andy',
    created_at: '2026-05-12T11:00:00Z',
    updated_at: '2026-05-12T11:00:00Z',
  position: 0,
  },
  {
    job_id: 'job-003',
    // Title: 2026.05.30 - 040 - CAP*TURES - Roadshow - Central@Chidlom
    job_number: '040',
    event_date: '2026-05-30',
    product_type: 'CAP*TURES',
    product_cat: 'Roadshow',
    product_name: 'Central',
    place: 'Chidlom',
    // รายละเอียดงาน
    event_display_name: 'Central Food Hall Sampling Weekend',
    event_time: '10.00-20.00',
    venue: 'Central Chidlom, G Floor Food Hall',
    job_detail_notes: 'CAP*TURES 2 action + food-themed props\nBackdrop ลูกค้า Central Food Hall theme\nAW อนุมัติแล้ว รอ props ส่ง',
    // ข้อมูลหน้างาน
    onsite_contact_name: 'Khun Nook',
    onsite_contact_phone: '062-333-0040',
    onsite_line_id: 'nook_central',
    install_point: 'หน้า Food Hall entrance ชั้น G',
    team_meeting_time: '07.30',
    onsite_notes: 'ต้องผ่าน loading bay B',
    staff_list: [],
    // Company Account
    company_account: {
      company_name: 'Central Food Retail Co., Ltd.',
      contact_point: 'Khun Nook',
      phone_number: '02-000-3333',
      line_id: '',
      email: 'nook@central.co.th',
      tax_id: '0105540000001',
      company_address: '1027 Ploenchit Rd, Lumpini, Bangkok',
      branch: 'Head Office',
      billing_notes: '',
      bank_name: 'BBL',
      bank_account_number: '3456700003',
      bank_account_name: 'Central Food Retail Co., Ltd.',
      bank_branch: 'สาขาชิดลม',
    },
    company_id: 'comp-009',
    contact_person_id: 'ctct-009',
    customer_name: 'Central Food Hall',
    customer_id: 'cust-009',
    lead_op_id: undefined,
    estimated_value: 75000,
    payment_status: 'unpaid',
    staff_status: 'confirmed',
    doc_status: 'ready',
    op_stage: 'OP_PREPARING_AW_DONE',
    owner: 'Fern',
    created_at: '2026-05-01T09:00:00Z',
    updated_at: '2026-05-15T14:00:00Z',
  position: 0,
  },
  {
    job_id: 'job-004',
    // Title: 2026.05.21 - 041 - LCA + Film - Event - Sephora@EastinGrand
    job_number: '041',
    event_date: '2026-05-21',
    product_type: 'LCA + Film',
    product_cat: 'Event',
    product_name: 'Sephora',
    place: 'EastinGrand',
    // รายละเอียดงาน
    event_display_name: 'Sephora staff party',
    event_time: '17.00-23.00',
    venue: 'Eastin Grand Hotel Phayathai',
    job_detail_notes: 'LCA Photobooth + Film Slide 3 action\nBackdrop ลูกค้า\nAll AW done. Props packed. Ready for final briefing.',
    // ข้อมูลหน้างาน
    onsite_contact_name: 'ป้อน',
    onsite_contact_phone: '063-005-3541',
    onsite_line_id: '',
    install_point: 'Ballroom ชั้น 3 ฝั่งขวา',
    team_meeting_time: '14.00',
    onsite_notes: 'นัดรวมทีม lobby ชั้น 1',
    staff_list: [],
    // Company Account
    company_account: {
      company_name: '',
      contact_point: '',
      phone_number: '',
      line_id: '',
      email: 'panut.khaw@gmail.com',
      tax_id: '',
      company_address: '',
      branch: '',
      billing_notes: '',
      bank_name: '',
      bank_account_number: '',
      bank_account_name: '',
      bank_branch: '',
    },
    company_id: 'comp-001',
    contact_person_id: 'ctct-001',
    customer_name: 'Sephora Thailand',
    customer_id: 'cust-001',
    lead_op_id: 'lop-001',
    estimated_value: 150000,
    payment_status: 'paid',
    staff_status: 'confirmed',
    doc_status: 'ready',
    op_stage: 'OP_PREPARING_AW_DONE',
    owner: 'Vitta',
    created_at: '2026-05-05T10:00:00Z',
    updated_at: '2026-05-17T09:00:00Z',
  position: 0,
  },
  {
    job_id: 'job-005',
    // Title: 2026.05.24 - 042 - GIF Booth - Event - LINEMAN@KVillage
    job_number: '042',
    event_date: '2026-05-24',
    product_type: 'GIF Booth',
    product_cat: 'Event',
    product_name: 'LINEMAN',
    place: 'KVillage',
    // รายละเอียดงาน
    event_display_name: 'LINE MAN Weekend Market',
    event_time: '11.00-21.00',
    venue: 'K Village Bangkok, Sukhumvit 26',
    job_detail_notes: 'GIF Booth 1 station พร้อม LINE MAN theme props\nBackdrop LINE MAN สีเขียว + ตัวละคร\nทุกอย่างพร้อมแล้ว. งานสุดสัปดาห์นี้',
    // ข้อมูลหน้างาน
    onsite_contact_name: 'Khun Kob',
    onsite_contact_phone: '089-900-0042',
    onsite_line_id: 'kob_lineman',
    install_point: 'ลานกลาง zone B',
    team_meeting_time: '08.30',
    onsite_notes: '',
    staff_list: [],
    // Company Account
    company_account: {
      company_name: 'Line Company (Thailand) Ltd.',
      contact_point: 'Khun Kob',
      phone_number: '02-000-5555',
      line_id: 'kob_lineman',
      email: 'kob@linecorp.th',
      tax_id: '0105558000001',
      company_address: 'Gaysorn Tower, Ploenchit',
      branch: 'Head Office',
      billing_notes: 'Credit 30 วัน',
      bank_name: 'SCB',
      bank_account_number: '5678900005',
      bank_account_name: 'Line Company (Thailand) Ltd.',
      bank_branch: 'สาขาเพลินจิต',
    },
    company_id: 'comp-010',
    contact_person_id: 'ctct-010',
    customer_name: 'LINE MAN Thailand',
    customer_id: 'cust-010',
    lead_op_id: undefined,
    estimated_value: 48000,
    payment_status: 'paid',
    staff_status: 'confirmed',
    doc_status: 'ready',
    op_stage: 'OP_READY_FOR_EVENT',
    owner: 'Nong',
    created_at: '2026-05-08T09:00:00Z',
    updated_at: '2026-05-18T10:00:00Z',
  position: 0,
  },
  {
    job_id: 'job-006',
    job_number: '043',
    event_date: '2026-05-28',
    product_type: 'CAP*TURES',
    product_cat: 'Roadshow',
    product_name: 'SiamParagon',
    place: 'SiamParagon',
    event_display_name: 'Siam Paragon Beauty Fest 2026',
    event_time: '10.00-21.00',
    venue: 'Siam Paragon G Floor, Beauty Hall',
    job_detail_notes: 'CAP*TURES Photobooth — 5 action slots\nBackdrop สีขาว floral ลูกค้าจัดเตรียม\nWaiting for signed TOR and 50% deposit before finalising staff.',
    onsite_contact_name: 'Khun Wan',
    onsite_contact_phone: '081-555-6677',
    onsite_line_id: 'wan_siam',
    install_point: 'G Floor ทางเข้าหลัก ฝั่ง BTS',
    team_meeting_time: '08.00',
    onsite_notes: 'Parking B2 ใช้บัตรกด — แจ้ง Wan ล่วงหน้า 1 วัน',
    staff_list: [],
    company_id: 'comp-011',
    contact_person_id: 'ctct-011',
    customer_name: 'Siam Paragon',
    customer_id: 'cust-011',
    lead_op_id: undefined,
    company_account: {
      company_name: 'Siam Paragon Development Co., Ltd.',
      contact_point: 'Khun Wan Sitthirat',
      phone_number: '02-610-8000',
      line_id: 'wan_siam',
      email: 'wan.events@siamparagon.co.th',
      tax_id: '0105537059873',
      company_address: '991 Rama I Rd, Pathum Wan, Bangkok 10330',
      branch: 'สำนักงานใหญ่',
      billing_notes: 'วางบิลทุกวันพุธ ส่งเอกสาร PDF ทาง email',
      bank_name: 'KBANK',
      bank_account_number: '6789000006',
      bank_account_name: 'Siam Paragon Development Co., Ltd.',
      bank_branch: 'สาขาสยามพารากอน',
    },
    estimated_value: 95000,
    payment_status: 'unpaid',
    staff_status: 'pending',
    doc_status: 'pending',
    op_stage: 'OP_WAIT_STAFF_PAYMENT_DOC_TERR',
    owner: 'Vitta',
    created_at: '2026-05-10T14:00:00Z',
    updated_at: '2026-05-16T11:00:00Z',
  position: 0,
  },
  {
    job_id: 'job-007',
    job_number: '036',
    event_date: '2025-11-11',
    product_type: 'CAP*TURES',
    product_cat: 'Campaign',
    product_name: 'Lazada1111',
    place: 'IconSiam',
    event_display_name: 'Lazada 11.11 Mega Campaign 2025',
    event_time: '10.00-22.00',
    venue: 'Icon Siam, Hall of Wonders, Zone C',
    job_detail_notes: 'CAP*TURES Photobooth — 8 action slots, custom AI filter\nBackdrop Lazada 11.11 ทีม Creative ลูกค้า\nCompleted. Invoice paid. Photos and videos delivered via WeTransfer.',
    onsite_contact_name: 'Khun Mint',
    onsite_contact_phone: '089-111-2233',
    onsite_line_id: 'mint_lazada',
    install_point: 'Hall of Wonders Zone C — ใกล้ escalator ชั้น 1',
    team_meeting_time: '07.30',
    onsite_notes: 'Loading dock Icon Siam ชั้น B — จอดรถนาน 2 ชม. แล้วย้าย',
    staff_list: [],
    company_id: 'comp-005',
    contact_person_id: 'ctct-005',
    customer_name: 'Lazada Thailand',
    customer_id: 'cust-005',
    lead_op_id: 'lop-005',
    company_account: {
      company_name: 'Lazada Thailand Co., Ltd.',
      contact_point: 'Khun Mint Pornpanich',
      phone_number: '02-018-0888',
      line_id: 'mint_lazada',
      email: 'mint.events@lazada.co.th',
      tax_id: '0105557107132',
      company_address: '29/F, Bhiraj Tower, 2096 Sukhumvit Rd, Bangkok 10110',
      branch: 'สำนักงานใหญ่',
      billing_notes: 'PO number required — ขอจาก Mint ก่อน issue invoice',
      bank_name: 'BBL',
      bank_account_number: '7890100007',
      bank_account_name: 'Lazada Thailand Co., Ltd.',
      bank_branch: 'สาขาสุขุมวิท',
    },
    estimated_value: 180000,
    payment_status: 'paid',
    staff_status: 'confirmed',
    doc_status: 'ready',
    op_stage: 'OP_DONE_PAYMENT',
    owner: 'Vitta',
    created_at: '2025-10-01T09:00:00Z',
    updated_at: '2025-11-15T12:00:00Z',
  position: 0,
  },
  {
    job_id: 'job-008',
    job_number: '037',
    event_date: '2025-12-20',
    product_type: 'Andy & Fine',
    product_cat: 'Event',
    product_name: 'Marriott',
    place: 'JWMarriottBKK',
    event_display_name: 'Marriott Thailand Staff Year-End Party 2025',
    event_time: '18.00-23.00',
    venue: 'JW Marriott Hotel Bangkok, Grand Ballroom',
    job_detail_notes: 'Andy & Fine Portrait Booth — 3 look sets\nBackdrop set 3 ชุด ทีมงานเตรียม\nAll done. Great feedback from client. Client wants to rebook Q4 2026.',
    onsite_contact_name: 'Khun Fah',
    onsite_contact_phone: '086-444-5566',
    onsite_line_id: 'fah_marriott',
    install_point: 'Grand Ballroom Foyer, ริมหน้าต่างมุมขวา',
    team_meeting_time: '15.00',
    onsite_notes: 'Valet parking ฟรี — แจ้ง Fah ให้ออก parking pass ล่วงหน้า',
    staff_list: [],
    company_id: 'comp-012',
    contact_person_id: 'ctct-012',
    customer_name: 'Marriott Hotels Thailand',
    customer_id: 'cust-012',
    lead_op_id: 'lop-006',
    company_account: {
      company_name: 'JW Marriott Bangkok',
      contact_point: 'Khun Fah Sirikanya',
      phone_number: '02-656-7700',
      line_id: 'fah_marriott',
      email: 'fah.events@marriott.com',
      tax_id: '0105520009876',
      company_address: '4 Sukhumvit Soi 2, Klongtoey, Bangkok 10110',
      branch: 'สำนักงานใหญ่',
      billing_notes: 'ส่ง invoice ทาง email ภายใน 7 วันหลังงาน',
      bank_name: 'TTB',
      bank_account_number: '8901200008',
      bank_account_name: 'JW Marriott Bangkok',
      bank_branch: 'สาขาสุขุมวิท 2',
    },
    estimated_value: 60000,
    payment_status: 'paid',
    staff_status: 'confirmed',
    doc_status: 'ready',
    op_stage: 'OP_DONE_PAYMENT',
    owner: 'Andy',
    created_at: '2025-11-01T10:00:00Z',
    updated_at: '2025-12-22T09:00:00Z',
  position: 0,
  },
]

// ─── Activities ──────────────────────────────────────────────────────────────
export const mockActivities: Activity[] = [
  {
    activity_id: 'act-001',
    entity_type: 'lead_opportunity',
    entity_id: 'lop-001',
    activity_type: 'call',
    title: 'Call logged',
    description: 'Discussed backdrop design and confirmed event details with Khun Pim.',
    created_by: 'Vitta',
    created_at: '2026-05-12T10:00:00Z',
  },
  {
    activity_id: 'act-002',
    entity_type: 'lead_opportunity',
    entity_id: 'lop-001',
    activity_type: 'email',
    title: 'Email logged',
    description: 'Sent quotation PDF. Waiting for approval.',
    created_by: 'Vitta',
    created_at: '2026-05-10T09:00:00Z',
  },
  {
    activity_id: 'act-003',
    entity_type: 'lead_opportunity',
    entity_id: 'lop-003',
    activity_type: 'note',
    title: 'Note added',
    description: 'LINE MAN confirmed 4 booths. Revised quote sent.',
    created_by: 'Fern',
    created_at: '2026-05-14T11:00:00Z',
  },
  {
    activity_id: 'act-004',
    entity_type: 'won_job',
    entity_id: 'job-004',
    activity_type: 'status_change',
    title: 'Moved to OP Preparing',
    description: 'AW assets approved by Sephora. Moving to preparation stage.',
    created_by: 'Vitta',
    created_at: '2026-05-15T14:00:00Z',
  },
  {
    activity_id: 'act-005',
    entity_type: 'customer',
    entity_id: 'cust-001',
    activity_type: 'note',
    title: 'Note added',
    description: 'Sephora confirmed they want to book again for Q3 2026.',
    created_by: 'Vitta',
    created_at: '2026-05-01T10:00:00Z',
  },
]

// ─── Tasks ───────────────────────────────────────────────────────────────────
export const mockTasks: Task[] = [
  {
    task_id: 'task-001',
    title: 'Send revised quote to KBANK',
    description: 'Include updated AW design fee and travel allowance.',
    due_date: '2026-05-20',
    priority: 'high',
    status: 'pending',
    linked_entity_type: 'lead_opportunity',
    linked_entity_id: 'lop-002',
    linked_entity_name: 'KBANK Staff Appreciation Day',
    owner: 'Andy',
    created_at: '2026-05-15T09:00:00Z',
  },
  {
    task_id: 'task-002',
    title: 'Collect deposit from Siam Paragon',
    description: 'Follow up on 50% deposit and signed TOR.',
    due_date: '2026-05-22',
    priority: 'high',
    status: 'pending',
    linked_entity_type: 'won_job',
    linked_entity_id: 'job-006',
    linked_entity_name: 'Siam Paragon Beauty Fest',
    owner: 'Vitta',
    created_at: '2026-05-16T10:00:00Z',
  },
  {
    task_id: 'task-003',
    title: 'Brief staff for LINE MAN event',
    description: 'Send briefing doc to all confirmed staff.',
    due_date: '2026-05-22',
    priority: 'medium',
    status: 'in_progress',
    linked_entity_type: 'won_job',
    linked_entity_id: 'job-005',
    linked_entity_name: 'LINE MAN Weekend Market',
    owner: 'Nong',
    created_at: '2026-05-18T08:00:00Z',
  },
  {
    task_id: 'task-004',
    title: 'Prepare backdrop mock for Chanel',
    description: 'Send 3 mock options to Khun Belle for approval.',
    due_date: '2026-05-25',
    priority: 'medium',
    status: 'pending',
    linked_entity_type: 'won_job',
    linked_entity_id: 'job-002',
    linked_entity_name: 'Chanel VIP Dinner',
    owner: 'Andy',
    created_at: '2026-05-14T11:00:00Z',
  },
  {
    task_id: 'task-005',
    title: 'Follow up LINE Thailand quotation',
    description: 'No response for 5 days. Call Khun Toy.',
    due_date: '2026-05-19',
    priority: 'high',
    status: 'done',
    linked_entity_type: 'lead_opportunity',
    linked_entity_id: 'lop-003',
    linked_entity_name: 'LINE Thailand Mid-Year Festival',
    owner: 'Fern',
    created_at: '2026-05-12T09:00:00Z',
  },
]
