import type { Customer, LeadOpportunity, WonJob, Activity, Task } from '@/types'

export const MOCK_USERS = ['Vitta', 'Andy', 'Fern', 'Nong']

// ─── Customers ───────────────────────────────────────────────────────────────
export const mockCustomers: Customer[] = [
  {
    customer_id: 'cust-001',
    company_name: 'Sephora Thailand',
    contact_person: 'Khun Pim',
    phone: '081-234-5678',
    email: 'pim.mkt@sephora.co.th',
    line_id: '@sephorath',
    social: '@sephorathailand',
    customer_type: 'brand',
    notes: 'Repeat client. Usually books LCA + Film combo. Prefers EastinGrand or EmQuartier.',
    created_at: '2025-01-10T09:00:00Z',
    updated_at: '2026-05-01T10:00:00Z',
  },
  {
    customer_id: 'cust-002',
    company_name: 'LINE Thailand',
    contact_person: 'Khun Toy',
    phone: '089-876-5432',
    email: 'toy@linecorp.th',
    line_id: 'toy_lineth',
    social: '@linethai_events',
    customer_type: 'brand',
    notes: 'Usually activates at Central World or Icon Siam. Big budgets.',
    created_at: '2025-03-15T10:00:00Z',
    updated_at: '2026-04-20T08:30:00Z',
  },
  {
    customer_id: 'cust-003',
    company_name: 'KBANK',
    contact_person: 'Khun Winn',
    phone: '062-111-2233',
    email: 'winn.event@kasikornbank.com',
    line_id: 'winn_kbank',
    social: '',
    customer_type: 'brand',
    notes: 'Corporate client. Staff parties and product launches.',
    created_at: '2025-06-01T08:00:00Z',
    updated_at: '2026-03-10T14:00:00Z',
  },
  {
    customer_id: 'cust-004',
    company_name: 'EastinGrand Sathorn',
    contact_person: 'Khun Ploy',
    phone: '02-210-8100',
    email: 'events@eastingrand.com',
    line_id: '',
    social: '',
    customer_type: 'venue',
    notes: 'Venue partner. Refer clients to us regularly.',
    created_at: '2025-07-01T07:00:00Z',
    updated_at: '2025-12-01T09:00:00Z',
  },
  {
    customer_id: 'cust-005',
    company_name: 'Lazada Thailand',
    contact_person: 'Khun Mint',
    phone: '096-555-7788',
    email: 'mint.brand@lazada.co.th',
    line_id: 'mint_lazada',
    social: '@lazadath',
    customer_type: 'brand',
    notes: '11.11, 12.12 campaigns. Good partner for SX Event.',
    created_at: '2025-08-20T09:00:00Z',
    updated_at: '2026-05-10T11:00:00Z',
  },
  {
    customer_id: 'cust-006',
    company_name: 'PTT Group',
    contact_person: 'Khun Som',
    phone: '081-400-9900',
    email: 'som.csr@pttplc.com',
    line_id: '',
    social: '',
    customer_type: 'brand',
    notes: 'CSR & Family Day events. Usually outdoor or PTT HQ.',
    created_at: '2025-09-05T08:00:00Z',
    updated_at: '2026-02-14T10:00:00Z',
  },
]

// ─── Leads & Opportunities ───────────────────────────────────────────────────
export const mockLeadOpportunities: LeadOpportunity[] = [
  {
    lead_op_id: 'lop-001',
    name: 'Sephora Annual Campaign 2026',
    customer_id: 'cust-001',
    customer_name: 'Sephora Thailand',
    contact_person: 'Khun Pim',
    service_type: 'CAP*TURES',
    event_date: '2026-07-15',
    venue: 'EastinGrand Sathorn',
    estimated_value: 150000,
    owner: 'Vitta',
    notes: 'Full CAP*TURES set + printed strips. Wants 3D backdrop design.',
    status: 'open',
    created_at: '2026-04-10T09:00:00Z',
    updated_at: '2026-05-12T10:00:00Z',
  },
  {
    lead_op_id: 'lop-002',
    name: 'KBANK Staff Appreciation Day',
    customer_id: 'cust-003',
    customer_name: 'KBANK',
    contact_person: 'Khun Winn',
    service_type: 'Andy & Fine',
    event_date: '2026-06-20',
    venue: 'KBANK HQ Auditorium',
    estimated_value: 85000,
    owner: 'Andy',
    notes: 'Branding with KBANK green. Staff of ~300 pax.',
    status: 'open',
    created_at: '2026-04-20T10:30:00Z',
    updated_at: '2026-05-10T09:00:00Z',
  },
  {
    lead_op_id: 'lop-003',
    name: 'LINE Thailand Mid-Year Festival',
    customer_id: 'cust-002',
    customer_name: 'LINE Thailand',
    contact_person: 'Khun Toy',
    service_type: 'SX Event',
    event_date: '2026-08-02',
    venue: 'Central World',
    estimated_value: 220000,
    owner: 'Fern',
    notes: 'Multi-day activation. 4 booths, LCA + Film + GIF.',
    status: 'open',
    created_at: '2026-05-01T08:00:00Z',
    updated_at: '2026-05-14T11:00:00Z',
  },
  {
    lead_op_id: 'lop-004',
    name: 'K.Nong + K.Tan Wedding Photo',
    customer_id: undefined,
    customer_name: 'K.Nong Thanaporn',
    contact_person: 'K.Nong',
    service_type: 'CAP*TURES',
    event_date: '2026-09-28',
    venue: 'Capella Bangkok',
    estimated_value: 45000,
    owner: 'Nong',
    notes: 'Private wedding. Romantic film strip style.',
    status: 'open',
    created_at: '2026-05-08T14:00:00Z',
    updated_at: '2026-05-08T14:00:00Z',
  },
  {
    lead_op_id: 'lop-005',
    name: 'Lazada 11.11 Campaign 2025',
    customer_id: 'cust-005',
    customer_name: 'Lazada Thailand',
    contact_person: 'Khun Mint',
    service_type: 'CAP*TURES',
    event_date: '2025-11-11',
    venue: 'Icon Siam',
    estimated_value: 180000,
    owner: 'Vitta',
    notes: 'Already confirmed and delivered. Invoice paid.',
    status: 'won',
    created_at: '2025-09-15T09:00:00Z',
    updated_at: '2025-11-15T12:00:00Z',
  },
  {
    lead_op_id: 'lop-006',
    name: 'Marriott Staff Year-End Party',
    customer_id: undefined,
    customer_name: 'Marriott Hotels Thailand',
    contact_person: 'Khun Fah',
    service_type: 'Andy & Fine',
    event_date: '2025-12-20',
    venue: 'JW Marriott Bangkok',
    estimated_value: 60000,
    owner: 'Andy',
    notes: 'Year-end dinner party. 200 pax. Won and delivered.',
    status: 'won',
    created_at: '2025-10-10T10:00:00Z',
    updated_at: '2025-12-22T09:00:00Z',
  },
  {
    lead_op_id: 'lop-007',
    name: 'AIS Summer Activation 2025',
    customer_id: undefined,
    customer_name: 'AIS',
    contact_person: 'Khun Mod',
    service_type: 'SX Event',
    event_date: '2025-06-15',
    venue: 'Siam Paragon',
    estimated_value: 300000,
    owner: 'Fern',
    notes: 'Budget too low after procurement cut.',
    status: 'lost',
    created_at: '2025-04-01T09:00:00Z',
    updated_at: '2025-05-20T16:00:00Z',
  },
]

// ─── Won Jobs (OP Kanban) ─────────────────────────────────────────────────────
export const mockWonJobs: WonJob[] = [
  {
    job_id: 'job-001',
    job_number: '038',
    event_name: 'MUJI Store Opening',
    customer_name: 'MUJI Thailand',
    customer_id: undefined,
    contact_person: 'Khun Aom',
    service_type: 'CAP*TURES',
    event_date: '2026-06-05',
    venue: 'MUJI Central Embassy',
    estimated_value: 55000,
    payment_status: 'unpaid',
    staff_status: 'pending',
    doc_status: 'pending',
    op_stage: 'WON_JOB_LIST',
    owner: 'Vitta',
    notes: 'New brand, needs full brand kit for backdrop.',
    lead_op_id: undefined,
    created_at: '2026-05-10T10:00:00Z',
    updated_at: '2026-05-10T10:00:00Z',
  },
  {
    job_id: 'job-002',
    job_number: '039',
    event_name: 'Chanel VIP Dinner',
    customer_name: 'Chanel Thailand',
    customer_id: undefined,
    contact_person: 'Khun Belle',
    service_type: 'Andy & Fine',
    event_date: '2026-06-12',
    venue: 'Capella Bangkok',
    estimated_value: 120000,
    payment_status: 'partial',
    staff_status: 'pending',
    doc_status: 'pending',
    op_stage: 'WON_JOB_LIST',
    owner: 'Andy',
    notes: 'VIP-only. Needs premium print paper.',
    lead_op_id: undefined,
    created_at: '2026-05-12T11:00:00Z',
    updated_at: '2026-05-12T11:00:00Z',
  },
  {
    job_id: 'job-003',
    job_number: '040',
    event_name: 'Central Food Hall Sampling',
    customer_name: 'Central Food Hall',
    customer_id: undefined,
    contact_person: 'Khun Nook',
    service_type: 'CAP*TURES',
    event_date: '2026-05-30',
    venue: 'Central Chidlom',
    estimated_value: 75000,
    payment_status: 'unpaid',
    staff_status: 'confirmed',
    doc_status: 'ready',
    op_stage: 'OP_PREPARING_AW_DONE',
    owner: 'Fern',
    notes: 'AW approved. Waiting for prop delivery.',
    lead_op_id: undefined,
    created_at: '2026-05-01T09:00:00Z',
    updated_at: '2026-05-15T14:00:00Z',
  },
  {
    job_id: 'job-004',
    job_number: '041',
    event_name: 'Sephora Radiant Campaign',
    customer_name: 'Sephora Thailand',
    customer_id: 'cust-001',
    contact_person: 'Khun Pim',
    service_type: 'LCA + Film',
    event_date: '2026-05-21',
    venue: 'EastinGrand Sathorn',
    estimated_value: 150000,
    payment_status: 'paid',
    staff_status: 'confirmed',
    doc_status: 'ready',
    op_stage: 'OP_PREPARING_AW_DONE',
    owner: 'Vitta',
    notes: 'All AW done. Props packed. Ready for final briefing.',
    lead_op_id: 'lop-001',
    created_at: '2026-05-05T10:00:00Z',
    updated_at: '2026-05-17T09:00:00Z',
  },
  {
    job_id: 'job-005',
    job_number: '042',
    event_name: 'LINE MAN Weekend Market',
    customer_name: 'LINE MAN Thailand',
    customer_id: undefined,
    contact_person: 'Khun Kob',
    service_type: 'GIF Booth',
    event_date: '2026-05-24',
    venue: 'K Village Bangkok',
    estimated_value: 48000,
    payment_status: 'paid',
    staff_status: 'confirmed',
    doc_status: 'ready',
    op_stage: 'OP_READY_FOR_EVENT',
    owner: 'Nong',
    notes: 'Everything ready. Event is this Saturday.',
    lead_op_id: undefined,
    created_at: '2026-05-08T09:00:00Z',
    updated_at: '2026-05-18T10:00:00Z',
  },
  {
    job_id: 'job-006',
    job_number: '043',
    event_name: 'Siam Paragon Beauty Fest',
    customer_name: 'Siam Paragon',
    customer_id: undefined,
    contact_person: 'Khun Wan',
    service_type: 'CAP*TURES',
    event_date: '2026-05-28',
    venue: 'Siam Paragon G Floor',
    estimated_value: 95000,
    payment_status: 'unpaid',
    staff_status: 'pending',
    doc_status: 'pending',
    op_stage: 'OP_WAIT_STAFF_PAYMENT_DOC_TERR',
    owner: 'Vitta',
    notes: 'Waiting for signed TOR and 50% deposit.',
    lead_op_id: undefined,
    created_at: '2026-05-10T14:00:00Z',
    updated_at: '2026-05-16T11:00:00Z',
  },
  {
    job_id: 'job-007',
    job_number: '036',
    event_name: 'Lazada 11.11 Campaign',
    customer_name: 'Lazada Thailand',
    customer_id: 'cust-005',
    contact_person: 'Khun Mint',
    service_type: 'CAP*TURES',
    event_date: '2025-11-11',
    venue: 'Icon Siam',
    estimated_value: 180000,
    payment_status: 'paid',
    staff_status: 'confirmed',
    doc_status: 'ready',
    op_stage: 'OP_DONE_PAYMENT',
    owner: 'Vitta',
    notes: 'Completed. Invoice paid. Photos delivered.',
    lead_op_id: 'lop-005',
    created_at: '2025-10-01T09:00:00Z',
    updated_at: '2025-11-15T12:00:00Z',
  },
  {
    job_id: 'job-008',
    job_number: '037',
    event_name: 'Marriott Staff Year-End',
    customer_name: 'Marriott Hotels Thailand',
    customer_id: undefined,
    contact_person: 'Khun Fah',
    service_type: 'Andy & Fine',
    event_date: '2025-12-20',
    venue: 'JW Marriott Bangkok',
    estimated_value: 60000,
    payment_status: 'paid',
    staff_status: 'confirmed',
    doc_status: 'ready',
    op_stage: 'OP_DONE_PAYMENT',
    owner: 'Andy',
    notes: 'All done. Great feedback from client.',
    lead_op_id: 'lop-006',
    created_at: '2025-11-01T10:00:00Z',
    updated_at: '2025-12-22T09:00:00Z',
  },
]

// ─── Activities ──────────────────────────────────────────────────────────────
export const mockActivities: Activity[] = [
  {
    activity_id: 'act-001',
    entity_type: 'lead_opportunity',
    entity_id: 'lop-001',
    activity_type: 'call',
    title: 'Call logged',
    description: 'Discussed backdrop design and confirmed event details with Khun Pim.',
    created_by: 'Vitta',
    created_at: '2026-05-12T10:00:00Z',
  },
  {
    activity_id: 'act-002',
    entity_type: 'lead_opportunity',
    entity_id: 'lop-001',
    activity_type: 'email',
    title: 'Email logged',
    description: 'Sent quotation PDF. Waiting for approval.',
    created_by: 'Vitta',
    created_at: '2026-05-10T09:00:00Z',
  },
  {
    activity_id: 'act-003',
    entity_type: 'lead_opportunity',
    entity_id: 'lop-003',
    activity_type: 'note',
    title: 'Note added',
    description: 'LINE MAN confirmed 4 booths. Revised quote sent.',
    created_by: 'Fern',
    created_at: '2026-05-14T11:00:00Z',
  },
  {
    activity_id: 'act-004',
    entity_type: 'won_job',
    entity_id: 'job-004',
    activity_type: 'status_change',
    title: 'Moved to OP Preparing',
    description: 'AW assets approved by Sephora. Moving to preparation stage.',
    created_by: 'Vitta',
    created_at: '2026-05-15T14:00:00Z',
  },
  {
    activity_id: 'act-005',
    entity_type: 'customer',
    entity_id: 'cust-001',
    activity_type: 'note',
    title: 'Note added',
    description: 'Sephora confirmed they want to book again for Q3 2026.',
    created_by: 'Vitta',
    created_at: '2026-05-01T10:00:00Z',
  },
]

// ─── Tasks ───────────────────────────────────────────────────────────────────
export const mockTasks: Task[] = [
  {
    task_id: 'task-001',
    title: 'Send revised quote to KBANK',
    description: 'Include updated AW design fee and travel allowance.',
    due_date: '2026-05-20',
    priority: 'high',
    status: 'pending',
    linked_entity_type: 'lead_opportunity',
    linked_entity_id: 'lop-002',
    linked_entity_name: 'KBANK Staff Appreciation Day',
    owner: 'Andy',
    created_at: '2026-05-15T09:00:00Z',
  },
  {
    task_id: 'task-002',
    title: 'Collect deposit from Siam Paragon',
    description: 'Follow up on 50% deposit and signed TOR.',
    due_date: '2026-05-22',
    priority: 'high',
    status: 'pending',
    linked_entity_type: 'won_job',
    linked_entity_id: 'job-006',
    linked_entity_name: 'Siam Paragon Beauty Fest',
    owner: 'Vitta',
    created_at: '2026-05-16T10:00:00Z',
  },
  {
    task_id: 'task-003',
    title: 'Brief staff for LINE MAN event',
    description: 'Send briefing doc to all confirmed staff.',
    due_date: '2026-05-22',
    priority: 'medium',
    status: 'in_progress',
    linked_entity_type: 'won_job',
    linked_entity_id: 'job-005',
    linked_entity_name: 'LINE MAN Weekend Market',
    owner: 'Nong',
    created_at: '2026-05-18T08:00:00Z',
  },
  {
    task_id: 'task-004',
    title: 'Prepare backdrop mock for Chanel',
    description: 'Send 3 mock options to Khun Belle for approval.',
    due_date: '2026-05-25',
    priority: 'medium',
    status: 'pending',
    linked_entity_type: 'won_job',
    linked_entity_id: 'job-002',
    linked_entity_name: 'Chanel VIP Dinner',
    owner: 'Andy',
    created_at: '2026-05-14T11:00:00Z',
  },
  {
    task_id: 'task-005',
    title: 'Follow up LINE Thailand quotation',
    description: 'No response for 5 days. Call Khun Toy.',
    due_date: '2026-05-19',
    priority: 'high',
    status: 'done',
    linked_entity_type: 'lead_opportunity',
    linked_entity_id: 'lop-003',
    linked_entity_name: 'LINE Thailand Mid-Year Festival',
    owner: 'Fern',
    created_at: '2026-05-12T09:00:00Z',
  },
]
