import type { Customer, Lead, Opportunity, WonProject, Activity, Task } from '@/types'

export const MOCK_USERS = ['Vitta', 'Andy', 'Fern', 'Nong']

export const mockCustomers: Customer[] = [
  {
    customer_id: 'cust-001',
    name: 'Pim Rattana',
    company_name: 'LYNK & CO Thailand',
    customer_type: 'brand',
    email: 'pim@lynkco.th',
    phone: '081-234-5678',
    line_id: '@pimrattana',
    instagram: '@pimrattana_',
    source: 'referral',
    tags: ['auto', 'premium', 'brand-activation'],
    notes: 'Key contact for Q4 brand activations. Very responsive on LINE.',
    owner: 'Vitta',
    created_at: '2025-09-10T09:00:00Z',
    updated_at: '2026-04-02T14:30:00Z',
  },
  {
    customer_id: 'cust-002',
    name: 'Khun Nattapat',
    company_name: 'True Corp',
    customer_type: 'brand',
    email: 'nattapat.k@truecorp.co.th',
    phone: '089-456-7890',
    line_id: '@nattapatk',
    instagram: '',
    source: 'website',
    tags: ['telco', 'large-event', 'repeat'],
    notes: 'Repeat client. Annual activation budget ~500K.',
    owner: 'Andy',
    created_at: '2025-06-15T10:00:00Z',
    updated_at: '2026-03-20T11:00:00Z',
  },
  {
    customer_id: 'cust-003',
    name: 'Sirinya W.',
    company_name: 'Mango Agency',
    customer_type: 'agency',
    email: 'sirinya@mangoagency.co.th',
    phone: '062-789-0123',
    line_id: '@sirinya_mango',
    instagram: '@sirinya.w',
    source: 'ig',
    tags: ['agency', 'fashion', 'wedding-adjacent'],
    notes: 'Works with luxury fashion brands. Prefers Andy & Fine.',
    owner: 'Vitta',
    created_at: '2025-11-01T08:00:00Z',
    updated_at: '2026-02-14T16:00:00Z',
  },
  {
    customer_id: 'cust-004',
    name: 'Khun Wichai',
    company_name: 'Centara Hotels',
    customer_type: 'venue',
    email: 'wichai.s@centara.co.th',
    phone: '094-321-0987',
    line_id: '@wichaicentara',
    instagram: '',
    source: 'event',
    tags: ['hotel', 'gala', 'corporate'],
    notes: 'Venue partner. Refers hotel clients for HNWI events.',
    owner: 'Fern',
    created_at: '2025-07-22T09:00:00Z',
    updated_at: '2026-01-30T10:00:00Z',
  },
  {
    customer_id: 'cust-005',
    name: 'Natnicha P.',
    company_name: '',
    customer_type: 'individual',
    email: 'natnicha.p@gmail.com',
    phone: '093-555-1234',
    line_id: '@nicha_weds',
    instagram: '@natnicha_wedding',
    source: 'ig',
    tags: ['wedding', 'personal', 'high-value'],
    notes: 'Planning a premium wedding with 300+ guests. Interested in Andy & Fine full package.',
    owner: 'Andy',
    created_at: '2026-01-05T12:00:00Z',
    updated_at: '2026-04-10T09:00:00Z',
  },
  {
    customer_id: 'cust-006',
    name: 'Pat Charoenwong',
    company_name: 'Ogilvy Thailand',
    customer_type: 'agency',
    email: 'pat.c@ogilvy.th',
    phone: '081-900-7654',
    line_id: '@pat_ogilvy',
    instagram: '',
    source: 'referral',
    tags: ['agency', 'large-scale', 'fmcg'],
    notes: 'Senior Account Director at Ogilvy. Big FMCG activations.',
    owner: 'Vitta',
    created_at: '2025-08-18T11:00:00Z',
    updated_at: '2026-04-01T14:00:00Z',
  },
]

export const mockLeads: Lead[] = [
  {
    lead_id: 'lead-001',
    contact_name: 'Teerapat J.',
    company_name: 'Grab Thailand',
    email: 'teerapat.j@grab.com',
    phone: '085-112-3344',
    line_id: '@teerapat_grab',
    source: 'website',
    interested_service: 'CAP*TURES',
    budget_range: '200,000 - 350,000 THB',
    event_date: '2026-07-15',
    event_location: 'BITEC Bangkok',
    lead_status: 'qualified',
    lead_score: 90,
    notes: 'Grab Tech Summit 2026. Looking for interactive photo experience.',
    owner: 'Vitta',
    created_at: '2026-05-01T09:00:00Z',
  },
  {
    lead_id: 'lead-002',
    contact_name: 'Mook Siriphun',
    company_name: '',
    email: 'mook.s@gmail.com',
    phone: '092-445-6677',
    line_id: '@mook_weds2026',
    source: 'ig',
    interested_service: 'Andy & Fine',
    budget_range: '80,000 - 120,000 THB',
    event_date: '2026-09-20',
    event_location: 'Sala Rattanakosin, Bangkok',
    lead_status: 'contacted',
    lead_score: 70,
    notes: 'Engaged, planning a 200-person intimate wedding. Saw us on IG.',
    owner: 'Andy',
    created_at: '2026-05-03T11:00:00Z',
  },
  {
    lead_id: 'lead-003',
    contact_name: 'Khun Pichaya',
    company_name: 'SCG Group',
    email: 'pichaya.w@scg.co.th',
    phone: '081-777-8899',
    line_id: '',
    source: 'referral',
    interested_service: 'SX Event',
    budget_range: '500,000+ THB',
    event_date: '2026-11-05',
    event_location: 'IMPACT Arena',
    lead_status: 'new',
    lead_score: 80,
    notes: 'Annual staff celebration. 1,000+ attendees. Referred by True Corp.',
    owner: 'Vitta',
    created_at: '2026-05-10T08:30:00Z',
  },
  {
    lead_id: 'lead-004',
    contact_name: 'Jane Thipawan',
    company_name: 'LINE Thailand',
    email: 'jane.t@linecorp.th',
    phone: '090-234-5566',
    line_id: '@janeline',
    source: 'line',
    interested_service: 'CAP*TURES',
    budget_range: '150,000 - 250,000 THB',
    event_date: '2026-06-28',
    event_location: 'True Digital Park',
    lead_status: 'contacted',
    lead_score: 85,
    notes: 'LINE Developer Conference. Wants AI mirror + mosaic wall combo.',
    owner: 'Fern',
    created_at: '2026-05-08T14:00:00Z',
  },
  {
    lead_id: 'lead-005',
    contact_name: 'Anon visitor',
    company_name: '',
    email: '',
    phone: '',
    line_id: '',
    source: 'walk-in',
    interested_service: 'Booth Rental',
    budget_range: 'Under 50,000 THB',
    event_date: '',
    event_location: 'TBD',
    lead_status: 'new',
    lead_score: 5,
    notes: 'Walked into office, curious about booth rental. No contact info left.',
    owner: 'Nong',
    created_at: '2026-05-12T15:30:00Z',
  },
  {
    lead_id: 'lead-006',
    contact_name: 'Krit Manassom',
    company_name: 'SCBX',
    email: 'krit.m@scbx.com',
    phone: '087-654-3210',
    line_id: '@krit_scbx',
    source: 'event',
    interested_service: 'Custom Activation',
    budget_range: '400,000 - 600,000 THB',
    event_date: '2026-08-20',
    event_location: 'SCB Park',
    lead_status: 'qualified',
    lead_score: 90,
    notes: 'Fintech event. Wants fully branded custom activation with data capture.',
    owner: 'Vitta',
    created_at: '2026-05-05T10:00:00Z',
  },
]

export const OPPORTUNITY_STAGES = [
  'New Opportunity',
  'Contacted',
  'Requirement Collected',
  'Proposal Sent',
  'Negotiation',
  'Confirmed',
  'Won',
  'Lost',
] as const

export const mockOpportunities: Opportunity[] = [
  {
    opportunity_id: 'opp-001',
    linked_customer_id: 'cust-001',
    linked_lead_id: undefined,
    deal_name: 'LYNK & CO Bangkok Motor Show',
    service_type: 'CAP*TURES',
    estimated_value: 320000,
    expected_close_date: '2026-05-30',
    event_date: '2026-06-15',
    stage: 'Proposal Sent',
    probability: 65,
    owner: 'Vitta',
    next_action: 'Follow up on proposal feedback',
    next_follow_up_date: '2026-05-16',
    notes: 'Client requested 2 revised proposal versions.',
    created_at: '2026-04-20T09:00:00Z',
    updated_at: '2026-05-10T14:00:00Z',
  },
  {
    opportunity_id: 'opp-002',
    linked_customer_id: 'cust-002',
    linked_lead_id: undefined,
    deal_name: 'True Move H Year-End Party',
    service_type: 'SX Event',
    estimated_value: 480000,
    expected_close_date: '2026-06-01',
    event_date: '2026-12-20',
    stage: 'Negotiation',
    probability: 75,
    owner: 'Andy',
    next_action: 'Finalize contract terms',
    next_follow_up_date: '2026-05-17',
    notes: 'Budget slightly over cap — negotiating package extras.',
    created_at: '2026-04-15T10:00:00Z',
    updated_at: '2026-05-12T11:00:00Z',
  },
  {
    opportunity_id: 'opp-003',
    linked_customer_id: 'cust-003',
    linked_lead_id: undefined,
    deal_name: 'Mango x Gucci Pop-Up Activation',
    service_type: 'Andy & Fine',
    estimated_value: 180000,
    expected_close_date: '2026-05-25',
    event_date: '2026-07-04',
    stage: 'Requirement Collected',
    probability: 50,
    owner: 'Vitta',
    next_action: 'Send proposal by Friday',
    next_follow_up_date: '2026-05-15',
    notes: 'Luxury aesthetic required. Film + digital combo.',
    created_at: '2026-05-01T09:00:00Z',
    updated_at: '2026-05-13T16:00:00Z',
  },
  {
    opportunity_id: 'opp-004',
    linked_customer_id: 'cust-006',
    linked_lead_id: undefined,
    deal_name: 'Ogilvy x P&G Brand Activation',
    service_type: 'CAP*TURES',
    estimated_value: 550000,
    expected_close_date: '2026-06-15',
    event_date: '2026-07-20',
    stage: 'Contacted',
    probability: 40,
    owner: 'Vitta',
    next_action: 'Book requirements call',
    next_follow_up_date: '2026-05-18',
    notes: 'Agency RFP still open — competing with 2 others.',
    created_at: '2026-05-05T11:00:00Z',
    updated_at: '2026-05-11T09:00:00Z',
  },
  {
    opportunity_id: 'opp-005',
    linked_customer_id: 'cust-005',
    linked_lead_id: undefined,
    deal_name: 'Natnicha & James Wedding',
    service_type: 'Andy & Fine',
    estimated_value: 120000,
    expected_close_date: '2026-05-20',
    event_date: '2026-09-20',
    stage: 'Confirmed',
    probability: 90,
    owner: 'Andy',
    next_action: 'Send contract and invoice',
    next_follow_up_date: '2026-05-15',
    notes: 'All details aligned. Awaiting signed contract.',
    created_at: '2026-05-06T10:00:00Z',
    updated_at: '2026-05-14T08:00:00Z',
  },
  {
    opportunity_id: 'opp-006',
    linked_customer_id: 'cust-004',
    linked_lead_id: undefined,
    deal_name: 'Centara New Year Gala',
    service_type: 'Andy & Fine',
    estimated_value: 95000,
    expected_close_date: '2026-05-30',
    event_date: '2026-12-31',
    stage: 'New Opportunity',
    probability: 20,
    owner: 'Fern',
    next_action: 'Initial intro call',
    next_follow_up_date: '2026-05-20',
    notes: 'Warm intro via venue manager.',
    created_at: '2026-05-13T14:00:00Z',
    updated_at: '2026-05-13T14:00:00Z',
  },
  {
    opportunity_id: 'opp-007',
    linked_customer_id: 'cust-002',
    linked_lead_id: 'lead-004',
    deal_name: 'LINE Developer Conference 2026',
    service_type: 'CAP*TURES',
    estimated_value: 210000,
    expected_close_date: '2026-06-10',
    event_date: '2026-06-28',
    stage: 'Proposal Sent',
    probability: 70,
    owner: 'Fern',
    next_action: 'Await decision by May 20',
    next_follow_up_date: '2026-05-20',
    notes: 'Strong interest. Decision pending internal budget approval.',
    created_at: '2026-05-09T09:00:00Z',
    updated_at: '2026-05-13T15:00:00Z',
  },
  {
    opportunity_id: 'opp-008',
    linked_customer_id: 'cust-001',
    linked_lead_id: undefined,
    deal_name: 'LYNK & CO Mid-Year Brand Day',
    service_type: 'Custom Activation',
    estimated_value: 160000,
    expected_close_date: '2026-04-15',
    event_date: '2026-04-28',
    stage: 'Lost',
    probability: 0,
    owner: 'Vitta',
    next_action: '',
    next_follow_up_date: '',
    notes: 'Lost to cheaper vendor. Consider better pricing for next round.',
    created_at: '2026-03-20T09:00:00Z',
    updated_at: '2026-04-15T16:00:00Z',
  },
]

export const mockWonProjects: WonProject[] = [
  {
    project_id: 'won-001',
    linked_opportunity_id: undefined,
    client_name: 'Grab Thailand',
    brand: 'GrabFood',
    service_used: 'CAP*TURES',
    project_date: '2025-11-15',
    project_value: 280000,
    location: 'BITEC Bangkok',
    campaign_goal: 'Brand awareness and social amplification for GrabFood campaign launch.',
    deliverables: ['360 Video Booth x2', 'AI Mirror x1', 'Digital mosaic wall', 'Same-day reel output'],
    result_summary: '4,200 photos shared on social. 18K reach on day-of. Client requested reactivation for Q1 2026.',
    photos_links: [],
    invoice_status: 'paid',
    reusable_case_study: true,
    reactivation_date: '2026-06-01',
    notes: 'One of our best-performing events. Benchmark for future F&B activations.',
  },
  {
    project_id: 'won-002',
    linked_opportunity_id: undefined,
    client_name: 'Khun Panisa & Khun Tawan',
    brand: 'Private Wedding',
    service_used: 'Andy & Fine',
    project_date: '2025-12-22',
    project_value: 145000,
    location: 'Capella Bangkok',
    campaign_goal: 'Luxury wedding photo experience with film-look aesthetic.',
    deliverables: ['Vintage film booth', 'Open-air Andy station', 'Physical prints x200', 'Digital gallery'],
    result_summary: 'Couple and guests loved the film aesthetic. Strong referral leads from event.',
    photos_links: [],
    invoice_status: 'paid',
    reusable_case_study: true,
    reactivation_date: undefined,
    notes: 'Perfect showcase for Andy & Fine premium tier.',
  },
  {
    project_id: 'won-003',
    linked_opportunity_id: undefined,
    client_name: 'TikTok Thailand',
    brand: 'TikTok',
    service_used: 'Custom Activation',
    project_date: '2026-02-14',
    project_value: 680000,
    location: 'Siam Discovery',
    campaign_goal: "Interactive Valentine's Day activation with creator content tools.",
    deliverables: ['Custom-built mirror booth', 'TikTok AR filter integration', 'Live feed wall', 'Operator x3', '2-day activation'],
    result_summary: '11,500 interactions. Trending on TikTok Thailand for 3 days. Client reactivating for Q3.',
    photos_links: [],
    invoice_status: 'paid',
    reusable_case_study: true,
    reactivation_date: '2026-08-01',
    notes: 'Landmark project. Use as flagship case study for Custom Activation pitch.',
  },
  {
    project_id: 'won-004',
    linked_opportunity_id: undefined,
    client_name: 'Mango Agency x Dior',
    brand: 'Dior Beauty',
    service_used: 'Andy & Fine',
    project_date: '2026-03-08',
    project_value: 195000,
    location: 'EmQuartier',
    campaign_goal: "Dior Beauty counter launch — luxury experience for Women's Day.",
    deliverables: ['Vintage booth x1', 'Branded print strips', 'Live IG frame overlay', 'Custom backdrop'],
    result_summary: 'High-end output matched Dior brand standard. Agency received strong client feedback.',
    photos_links: [],
    invoice_status: 'paid',
    reusable_case_study: true,
    reactivation_date: undefined,
    notes: "Great reference for luxury/beauty brands.",
  },
  {
    project_id: 'won-005',
    linked_opportunity_id: undefined,
    client_name: 'PTT Global Chemical',
    brand: 'GC Group',
    service_used: 'SX Event',
    project_date: '2026-01-20',
    project_value: 420000,
    location: 'Royal Cliff Resort, Pattaya',
    campaign_goal: 'Annual leadership retreat — engagement & team building activities.',
    deliverables: ['Photo zone setup', 'Live slideshow', 'Custom gifting station', 'Event MC support', 'Same-day video'],
    result_summary: 'Full-day event for 600 attendees. Client confirmed annual contract.',
    photos_links: [],
    invoice_status: 'paid',
    reusable_case_study: false,
    reactivation_date: '2027-01-15',
    notes: 'Annual deal locked. Flag for early renewal outreach in Nov 2026.',
  },
]

export const mockActivities: Activity[] = [
  {
    activity_id: 'act-001',
    entity_type: 'customer',
    entity_id: 'cust-001',
    activity_type: 'call',
    title: 'Discovery call with Pim',
    description: 'Discussed LYNK & CO Motor Show requirements. Budget confirmed at 300-350K.',
    created_by: 'Vitta',
    created_at: '2026-04-22T10:00:00Z',
  },
  {
    activity_id: 'act-002',
    entity_type: 'opportunity',
    entity_id: 'opp-001',
    activity_type: 'proposal_sent',
    title: 'Proposal v1 sent',
    description: 'Sent initial proposal PDF via email. Includes 360 booth + AI mirror package.',
    created_by: 'Vitta',
    created_at: '2026-05-01T14:30:00Z',
  },
  {
    activity_id: 'act-003',
    entity_type: 'opportunity',
    entity_id: 'opp-001',
    activity_type: 'follow_up',
    title: 'Follow-up on proposal',
    description: 'Client asked for alternative pricing. Will revise and resend.',
    created_by: 'Vitta',
    created_at: '2026-05-08T11:00:00Z',
  },
  {
    activity_id: 'act-004',
    entity_type: 'lead',
    entity_id: 'lead-001',
    activity_type: 'status_change',
    title: 'Lead qualified',
    description: 'Confirmed event date and budget. Moved to qualified.',
    created_by: 'Vitta',
    created_at: '2026-05-05T09:00:00Z',
  },
  {
    activity_id: 'act-005',
    entity_type: 'customer',
    entity_id: 'cust-002',
    activity_type: 'note',
    title: 'Budget confirmed for Dec event',
    description: 'True Corp confirmed annual event budget. Green light to scope SX Event package.',
    created_by: 'Andy',
    created_at: '2026-04-18T16:00:00Z',
  },
  {
    activity_id: 'act-006',
    entity_type: 'opportunity',
    entity_id: 'opp-005',
    activity_type: 'deal_won',
    title: 'Deal confirmed!',
    description: 'Natnicha & James signed the contract. Deposit received.',
    created_by: 'Andy',
    created_at: '2026-05-14T08:30:00Z',
  },
]

export const mockTasks: Task[] = [
  {
    task_id: 'task-001',
    title: 'Send revised proposal to LYNK & CO',
    description: 'Revise pricing for 360 booth, reduce setup fee, and add optional AI mirror upsell.',
    due_date: '2026-05-16',
    priority: 'high',
    status: 'pending',
    linked_entity_type: 'opportunity',
    linked_entity_id: 'opp-001',
    linked_entity_name: 'LYNK & CO Bangkok Motor Show',
    owner: 'Vitta',
    created_at: '2026-05-14T09:00:00Z',
  },
  {
    task_id: 'task-002',
    title: 'Send contract to Natnicha',
    description: 'Finalize wedding contract and send invoice for 50% deposit.',
    due_date: '2026-05-15',
    priority: 'high',
    status: 'pending',
    linked_entity_type: 'opportunity',
    linked_entity_id: 'opp-005',
    linked_entity_name: 'Natnicha & James Wedding',
    owner: 'Andy',
    created_at: '2026-05-14T08:00:00Z',
  },
  {
    task_id: 'task-003',
    title: 'Follow up with Krit @ SCBX',
    description: 'Check status on internal budget approval for Custom Activation.',
    due_date: '2026-05-18',
    priority: 'medium',
    status: 'pending',
    linked_entity_type: 'lead',
    linked_entity_id: 'lead-006',
    linked_entity_name: 'Krit Manassom - SCBX',
    owner: 'Vitta',
    created_at: '2026-05-12T10:00:00Z',
  },
  {
    task_id: 'task-004',
    title: 'Create SCG Group proposal draft',
    description: 'Scope SX Event package for 1,000+ pax at IMPACT Arena.',
    due_date: '2026-05-20',
    priority: 'high',
    status: 'in_progress',
    linked_entity_type: 'lead',
    linked_entity_id: 'lead-003',
    linked_entity_name: 'Khun Pichaya - SCG Group',
    owner: 'Vitta',
    created_at: '2026-05-11T14:00:00Z',
  },
  {
    task_id: 'task-005',
    title: 'Book intro call with Centara',
    description: 'Schedule 30-min intro call with Khun Wichai for New Year Gala.',
    due_date: '2026-05-20',
    priority: 'low',
    status: 'pending',
    linked_entity_type: 'opportunity',
    linked_entity_id: 'opp-006',
    linked_entity_name: 'Centara New Year Gala',
    owner: 'Fern',
    created_at: '2026-05-13T14:30:00Z',
  },
  {
    task_id: 'task-006',
    title: 'Upload TikTok case study assets',
    description: 'Add photos and video clips from TikTok activation to Won Deck.',
    due_date: '2026-05-17',
    priority: 'medium',
    status: 'pending',
    linked_entity_type: undefined,
    linked_entity_id: undefined,
    linked_entity_name: undefined,
    owner: 'Fern',
    created_at: '2026-05-10T11:00:00Z',
  },
]
